database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5432"
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_DB: panorama
    POSTGRES_USER: panorama


web:
  build: ./web
  ports:
    - "8000"
  links:
    - database:database
  volumes:
    - $PWD/reports:/app/reports
    - $PWD/web/panorama/panoramas_test:/app/panoramas_test
    - $PWD/panoramas_test/output:/app/panoramas_test/2016/output
  environment:
    SECRET_KEY: hoi
    DB_NAME: panorama
    DB_PASSWORD: insecure


render:
  build: ./web
  dockerfile: Dockerfile-render
  links:
    - database:database
  volumes:
    - $PWD/web/panorama/panoramas_test:/app/panoramas_test
  environment:
    SECRET_KEY: hoi
    DB_NAME: panorama
    DB_PASSWORD: insecure
