database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5454:5432"
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_DB: panorama
    POSTGRES_USER: panorama


web:
  build: ./web
  ports:
    - "8087:8000"
  links:
    - database:database
  volumes:
    - $PWD/web/panorama/panoramas_test:/app/panoramas_test
    - $PWD/test_output:/app/test_output
  environment:
    SECRET_KEY: hoi
    DB_NAME: panorama
    DB_PASSWORD: insecure
    PANORAMA_IMAGE_URL: https://acc.atlas.amsterdam.nl/panorama
    OBJECTSTORE_PASSWORD:


demo:
  build: ./demo
  ports:
    - "8088:80"
  volumes:
    - "./demo/html:/var/www/html/demo"
    - "./web/panorama/panoramas_test/2016:/var/www/html/2016"

