version: "3.7"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5454:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: panorama
      POSTGRES_USER: panorama
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  web:
    build: ./web
    ports:
      - "8087:8000"
    links:
      - database:database
    volumes:
      - $PWD/web/panorama/panoramas_test:/app/panoramas_test
      - $PWD/test_output:/app/test_output
    environment:
      SECRET_KEY: hoi
      DB_NAME: panorama
      DB_PASSWORD: insecure
      PANORAMA_IMAGE_URL: https://acc.panorama.data.amsterdam.nl/panorama
      OBJECTSTORE_USER:
      OBJECTSTORE_PASSWORD:
      PANORAMA_TENANT_ID:
      DATAPUNT_TENANT_ID:
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "panorama.wsgi:application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/panorama/static=/static"
      UWSGI_DIE_ON_TERM: 1

  demo:
    build: ./demo
    ports:
      - "8088:80"
    volumes:
      - "./demo/html:/var/www/html/demo"
      - "./test_output:/var/www/html/img"
