database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5454:5432"
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_DB: openpanorama
    POSTGRES_USER: openpanorama


web:
  build: ./web
  ports:
    - "8098:8000"
  links:
    - database:database
  volumes:
    - $PWD/reports:/app/reports
  environment:
    SECRET_KEY: hoi
    DB_NAME: openpanorama
    DB_PASSWORD: insecure
