version: "3.7"
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: panorama
    volumes:
      - ./backups:/tmp/backups
    shm_size: '4gb'

  importer:
    image: docker-registry.data.amsterdam.nl/datapunt/panorama:${ENVIRONMENT}
    links:
      - database:database
    environment:
      DB_NAME: panorama
      DB_USER: panorama
      DB_PASSWORD: insecure
      OBJECTSTORE_PASSWORD:
    command: >
      bash -c "python manage.py import_increments ${IMPORT_ARGS}"
