"""Objectstore settings."""


import os


RUNNING_OS_INTERNALLY = bool(os.getenv('RUNNING_OS_INTERNALLY', False))

# Objectstore user/password.
OBJECTSTORE_PASSWORD = os.getenv('OBJECTSTORE_PASSWORD', 'insecure')
OBJECTSTORE_USER = os.getenv('OBJECTSTORE_USER', 'panorama')

AUTH_VERSION = '2.0'
AUTHURL = 'https://identity.stack.cloudvps.com/v2.0'

# Datapunt objectstore.
DATAPUNT_OBJECTSTORE_USER = OBJECTSTORE_USER
DATAPUNT_OBJECTSTORE_PASSWORD = OBJECTSTORE_PASSWORD
DATAPUNT_TENANT_NAME = os.getenv('DATAPUNT_TENANT_NAME', 'BGE000081 Datapunt')
DATAPUNT_TENANT_ID = os.getenv('DATAPUNT_TENANT_ID', 'ffb7a5a57dd34cc49436abc510cad162')
DATAPUNT_CONTAINER = 'panorama'

# Panorama objectstore.
PANORAMA_OBJECTSTORE_USER = OBJECTSTORE_USER
PANORAMA_OBJECTSTORE_PASSWORD = OBJECTSTORE_PASSWORD
PANORAMA_TENANT_NAME = os.getenv('PANORAMA_TENANT_NAME', 'BGE000081 Panorama')
PANORAMA_TENANT_ID = os.getenv('PANORAMA_TENANT_ID', '3206eec333a04cc980799f75a593505a')
# Wait for new years to be uploaded:
PANORAMA_CONTAINERS = ['2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023']

REGION_NAME = 'NL'
