"""Objectstore settings."""


import os


RUNNING_OS_INTERNALLY = bool(os.getenv('RUNNING_OS_INTERNALLY', False))

# Fallback.
OBJECTSTORE_PASSWORD = os.getenv('OBJECTSTORE_PASSWORD', 'insecure')

AUTH_VERSION = '2.0'
AUTHURL = 'https://identity.stack.cloudvps.com/v2.0'

DATAPUNT_OBJECTSTORE_USER = os.getenv('OBJECTSTORE_USER', 'panorama')
# Backwards compatibility.
DATAPUNT_OBJECTSTORE_PASSWORD = os.getenv('DATAPUNT_OBJECTSTORE_PASSWORD', OBJECTSTORE_PASSWORD)
DATAPUNT_TENANT_NAME = os.getenv('DATAPUNT_TENANT_NAME', 'BGE000081 Datapunt')
DATAPUNT_TENANT_ID = os.getenv('DATAPUNT_TENANT_ID', 'ffb7a5a57dd34cc49436abc510cad162')
DATAPUNT_CONTAINER = 'panorama'

PANORAMA_OBJECTSTORE_USER = os.getenv('OBJECTSTORE_USER', 'panorama')
# Backwards compatibility.
PANORAMA_OBJECTSTORE_PASSWORD = os.getenv('PANORAMA_OBJECTSTORE_PASSWORD', OBJECTSTORE_PASSWORD)
PANORAMA_TENANT_NAME = os.getenv('PANORAMA_TENANT_NAME', 'BGE000081 Panorama')
PANORAMA_TENANT_ID = os.getenv('PANORAMA_TENANT_ID', '3206eec333a04cc980799f75a593505a')
# Wait for new years to be uploaded:
PANORAMA_CONTAINERS = ['2016', '2017', '2018', '2019', '2020', '2021', '2022']

REGION_NAME = 'NL'
