# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 11:13
from __future__ import unicode_literals

from django.db import migrations

from geo_views import migrate


class Migration(migrations.Migration):

    dependencies = [
            ('sites', '0001_initial'),
            ('panoramas', '0001_initial')
    ]

    operations = [
        migrate.ManageView(
            # pp = PanoramaPhoto
            # site.domain || 'panoramas/panorama/' || pp.pano_id || '/' AS uri,
            # 'panoramas/panorama' AS type,
            # site.name = 'API Domain'
            view_name="geo_panoramas_panoramafotopunt",
            sql="""
SELECT
    pp.id,
    pp.pano_id as display,
    pp.roll,
    pp.pitch,
    pp.heading,
    pp.geolocation AS geometrie
FROM
    panoramas_panorama pp,
    django_site site
WHERE
    site.id = 1
AND
    pp.geolocation IS NOT NULL
"""
        ),

    ]
