version: "3.7"
services:
  database:
    image: 127.0.0.1:5000/stackdb
    build: ./database
    networks:
      - default
    deploy:
      mode: global
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: panorama
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  dataloader:
    build:
      context: ../web
      dockerfile: WorkerDockerfile
    image: 127.0.0.1:5000/stackdataloader
    links:
      - database:database
    networks:
      - default
    environment:
      DATABASE_PORT_5432_TCP_ADDR: database
      DATABASE_PORT_5432_TCP_PORT: 5432
      DATABASE_NAME: panorama
      DATABASE_USER: panorama
      DATABASE_PASSWORD: insecure
      OBJECTSTORE_USER:
      OBJECTSTORE_PASSWORD:
      PANORAMA_TENANT_ID:
      DATAPUNT_TENANT_ID:
    deploy:
      restart_policy:
        condition: none
        delay: 5s
        max_attempts: 1
      replicas: 1
    command: >
      bash -c "sleep 60 && python manage.py migrate && python manage.py load_data"

  worker:
    build:
      context: ../web
      dockerfile: WorkerDockerfile
    image: 127.0.0.1:5000/stackworker
    links:
      - database:database
    networks:
      - default
    environment:
      DATABASE_PORT_5432_TCP_ADDR: database
      DATABASE_PORT_5432_TCP_PORT: 5432
      DATABASE_NAME: panorama
      DATABASE_USER: panorama
      DATABASE_PASSWORD: insecure
      OBJECTSTORE_USER:
      OBJECTSTORE_PASSWORD:
      PANORAMA_TENANT_ID:
      DATAPUNT_TENANT_ID:
    deploy:
      replicas: 2
