# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 11:13
from __future__ import unicode_literals

from django.db import migrations
from geo_views import migrate


class Migration(migrations.Migration):
    dependencies = [
        ('panoramas', '0001_initial')
    ]

    operations = [
        migrate.ManageView(
            view_name="geo_panoramas_panoramafotopunt",
            sql="""
SELECT
    pp.id,
    pp.pano_id as display,
    pp.roll,
    pp.pitch,
    pp.heading,
    pp.timestamp,
    pp.geolocation AS geometrie,
    'https://acc.atlas.amsterdam.nl/panorama' || pp.path || '/' ||
    pp.filename AS url, 'panoramas/opnamelocatie/' || pp.pano_id || '/' AS uri
FROM
    panoramas_panorama pp
AND
    pp.geolocation IS NOT NULL
"""
        ),
    ]
